(* This file has been automatically generated by lagrangians.py *)
ParameterDefinitions = {
	(* new parameters *)
	{mϕ2, {Description -> "BSM parameter mϕ2",
			LaTeX -> "mphi2",
			OutputName -> "m_{\\phi}^{2}"
		}
	},
	{λ1, {Description -> "BSM parameter λ1",
			LaTeX -> "lambda1",
			OutputName -> "\\lambda_{1}"
		}
	},
	{λ2, {Description -> "BSM parameter λ2",
			LaTeX -> "lambda2",
			OutputName -> "\\lambda_{2}"
		}
	},
	{λ3, {Description -> "BSM parameter λ3",
			LaTeX -> "lambda3",
			OutputName -> "\\lambda_{3}"
		}
	},
	{mΨ, {Description -> "BSM parameter mΨ",
			LaTeX -> "mCPsi",
			OutputName -> "m_{\\Psi}"
		}
	},
	{mψψp, {Description -> "BSM parameter mψψp",
			LaTeX -> "mpsipsip",
			OutputName -> "m_{\\psi\\psi'}"
		}
	},
	{λ4, {Description -> "BSM parameter λ4",
			LaTeX -> "lambda4",
			OutputName -> "\\lambda_{4}"
		}
	},
	{λ5, {Description -> "BSM parameter λ5",
			LaTeX -> "lambda5",
			OutputName -> "\\lambda_{5}"
		}
	},
	{λ6, {Description -> "BSM parameter λ6",
			LaTeX -> "lambda6",
			OutputName -> "\\lambda_{6}"
		}
	},

	(* Standard Model parameters *)
	{g1,        {Description -> "Hypercharge-Coupling"}},
	{g2,        {Description -> "Left-Coupling"}},
	{g3,        {Description -> "Strong-Coupling"}},
	{AlphaS,    {Description -> "Alpha Strong"}},
	{e,         {Description -> "electric charge"}},

	{Gf,        {Description -> "Fermi's constant"}},
	{aEWinv,    {Description -> "inverse weak coupling constant at mZ"}},

	{Yu,        {Description -> "Up-Yukawa-Coupling",
					DependenceNum -> Sqrt[2]/v * {
						{Mass[Fu,1], 0, 0},
						{0, Mass[Fu,2], 0},
						{0, 0, Mass[Fu,3]}
					}
				}
	},
	{Yd,        {Description -> "Down-Yukawa-Coupling",
					DependenceNum -> Sqrt[2]/v * {
						{Mass[Fd,1], 0, 0},
						{0, Mass[Fd,2], 0},
						{0, 0, Mass[Fd,3]}
					}
				}
	},
	{Ye,        {Description -> "Lepton-Yukawa-Coupling",
					DependenceNum -> Sqrt[2]/v * {
						{Mass[Fe,1], 0, 0},
						{0, Mass[Fe,2], 0},
						{0, 0, Mass[Fe,3]}
					}
				}
	},


	{mu2,       {Description -> "SM Mu Parameter"}},
	{\[Lambda], {Description -> "SM Higgs Selfcouplings",
					DependenceNum -> Mass[hh]^2/(v^2)
				}
	},
	{v,         {Description -> "EW-VEV",
					DependenceNum -> Sqrt[4 * Mass[VWp]^2/(g2^2)],
					DependenceSPheno -> None
				}
	},
	{mH2,       {Description -> "SM Higgs Mass Parameter"}},

	{ThetaW,    {Description -> "Weinberg-Angle",
					DependenceNum -> ArcSin[Sqrt[1 - Mass[VWp]^2/Mass[VZ]^2]]
				}
	},

	{ZZ,        {Description -> "Photon-Z Mixing Matrix"}},
	{ZW,        {Description -> "W Mixing Matrix",
					Dependence -> 1/Sqrt[2] {
						{1, 1},
						{\[ImaginaryI], -\[ImaginaryI]}
					}
				}
	},

	{Vu,        {Description -> "Left-Up-Mixing-Matrix"}},
	{Vd,        {Description -> "Left-Down-Mixing-Matrix"}},
	{Uu,        {Description -> "Right-Up-Mixing-Matrix"}},
	{Ud,        {Description -> "Right-Down-Mixing-Matrix"}},
	{Ve,        {Description -> "Left-Lepton-Mixing-Matrix"}},
	{Ue,        {Description -> "Right-Lepton-Mixing-Matrix"}}
};
