(* This file has been automatically generated by lagrangians.py *)
ParticleDefinitions[GaugeES] = {
	(* new fields *)
	{Ψ0, {Description -> "BSM field Ψ0",
			LaTeX -> "CPsi0",
			OutputName -> "\\Psi0",
			ElectricCharge -> 0
		}
	},
	{ψpp, {Description -> "BSM field ψ'+",
			LaTeX -> "psipp",
			OutputName -> "\\psi'+",
			ElectricCharge -> 1
		}
	},
	{ψp0, {Description -> "BSM field ψ'0",
			LaTeX -> "psip0",
			OutputName -> "\\psi'0",
			ElectricCharge -> 0
		}
	},
	{ϕp, {Description -> "BSM field ϕ+",
			LaTeX -> "phip",
			OutputName -> "\\phi+",
			ElectricCharge -> 1
		}
	},
	{ϕ0, {Description -> "BSM field ϕ0",
			LaTeX -> "phi0",
			OutputName -> "\\phi0",
			ElectricCharge -> 0
		}
	},
	{ψ0, {Description -> "BSM field ψ0",
			LaTeX -> "psi0",
			OutputName -> "\\psi0",
			ElectricCharge -> 0
		}
	},
	{ψm, {Description -> "BSM field ψ-",
			LaTeX -> "psim",
			OutputName -> "\\psi-",
			ElectricCharge -> -1
		}
	},

	(* Standard Model *)
	{H0, {
			PDG -> {0},
			Width -> 0,
			Mass -> Automatic,
			FeynArtsNr -> 1,
			LaTeX -> "H^0",
			OutputName -> "H0"
		}
	},
	{Hp, {
			PDG -> {0},
			Width -> 0,
			Mass -> Automatic,
			FeynArtsNr -> 2,
			LaTeX -> "H^+",
			OutputName -> "Hp"
		}
	},

	{VB,  {Description -> "B-Boson"}},
	{VG,  {Description -> "Gluon"}},
	{VWB, {Description -> "W-Bosons"}},
	{gB,  {Description -> "B-Boson Ghost"}},
	{gG,  {Description -> "Gluon Ghost"}},
	{gWB, {Description -> "W-Boson Ghost"}}
};

ParticleDefinitions[EWSB] = {
	(* new fields *)
	(* to be completed manually *)

	(* Standard Model *)
	{hh,   {Description -> "Higgs",
			PDG -> {25},
			PDG.IX -> {101000001}
		}
	},
	{Ah,   {Description -> "Pseudo-Scalar Higgs",
			PDG -> {0},
			PDG.IX -> {0},
			Mass -> {0},
			Width -> {0}
		}
	},
	{Hp,   {Description -> "Charged Higgs",
			PDG -> {0},
			PDG.IX -> {0},
			Width -> {0},
			Mass -> {0},
			LaTeX -> {"H^+", "H^-"},
			OutputName -> {"Hp", "Hm"},
			ElectricCharge -> 1
		}
	},

	{VP,   {Description -> "Photon"}},
	{VZ,   {Description -> "Z-Boson",
			Goldstone -> Ah
		}
	},
	{VG,   {Description -> "Gluon"}},
	{VWp,  {Description -> "W+ - Boson",
			Goldstone -> Hp
		}
	},
	{gP,   {Description -> "Photon Ghost"}},
	{gWp,  {Description -> "Positive W+ - Boson Ghost"}},
	{gWpC, {Description -> "Negative W+ - Boson Ghost"}},
	{gZ,   {Description -> "Z-Boson Ghost"}},
	{gG,   {Description -> "Gluon Ghost"}},

	{Fd,   {Description -> "Down-Quarks"}},
	{Fu,   {Description -> "Up-Quarks"}},
	{Fe,   {Description -> "Leptons"}},
	{Fv,   {Description -> "Neutrinos"}}
};

WeylFermionAndIndermediate = {
	(* new fields *)
	{Ψ, {LaTeX -> "\\Psi"}},
	{ψp, {LaTeX -> "\\psi'"}},
	{ϕ, {LaTeX -> "\\phi"}},
	{ψ, {LaTeX -> "\\psi"}},

	(* Standard Model *)
	{H, {
			PDG -> {0},
			Width -> 0,
			Mass -> Automatic,
			LaTeX -> "H",
			OutputName -> ""
		}
	},

	{dR,  {LaTeX -> "d_R"}},
	{eR,  {LaTeX -> "e_R"}},
	{l,   {LaTeX -> "l"}},
	{uR,  {LaTeX -> "u_R"}},
	{q,   {LaTeX -> "q"}},
	{eL,  {LaTeX -> "e_L"}},
	{dL,  {LaTeX -> "d_L"}},
	{uL,  {LaTeX -> "u_L"}},
	{vL,  {LaTeX -> "\\nu_L"}},

	{DR,  {LaTeX -> "D_R"}},
	{ER,  {LaTeX -> "E_R"}},
	{UR,  {LaTeX -> "U_R"}},
	{EL,  {LaTeX -> "E_L"}},
	{DL,  {LaTeX -> "D_L"}},
	{UL,  {LaTeX -> "U_L"}}
};
