(* This file has been automatically generated by lagrangians.py *)
Off[General::spell]

Model`Name = "T13Balpha0";
Model`NameLaTeX = "T1-3-B (\\alpha = 0)";
Model`Authors = "lagrangians.py (automatically generated)";
Model`Date = "2018-05-09";

(*-------------------------------------------*)
(*   particle content                        *)
(*-------------------------------------------*)

(* global symmetries *)
(* discrete ℤ₂ symmetry *)
Global[[1]] = {Z[2], Z2};

(* gauge groups *)
Gauge[[1]] = {B,   U[1], hypercharge, g1, False, 1};
Gauge[[2]] = {WB, SU[2], left,        g2, True,  1};
Gauge[[3]] = {G,  SU[3], color,       g3, False, 1};

(* matter fields *)
(*                   {name, gens, components, Y/2,  SU(2), SU(3), global} *)
(* Standard Model *)
FermionFields[[1]] = {q,    3,    {uL, dL},    1/6, 2,     3,     1};
FermionFields[[2]] = {l,    3,    {vL, eL},   -1/2, 2,     1,     1};
FermionFields[[3]] = {d,    3,    conj[dR],    1/3, 1,    -3,     1};
FermionFields[[4]] = {u,    3,    conj[uR],   -2/3, 1,    -3,     1};
FermionFields[[5]] = {e,    3,    conj[eR],      1, 1,     1,     1};

ScalarFields[[1]]  = {H,    1,    {Hp, H0},    1/2, 2,     1,     1};

(* new fields *)
FermionFields[[6]] = {Ψ, 1, Ψ0, 0, 1, 1, -1};
FermionFields[[7]] = {ψp, 1, {ψpp, ψp0}, 1/2, 2, 1, -1};
FermionFields[[8]] = {ψ, 1, {ψ0, ψm}, -1/2, 2, 1, -1};
ScalarFields[[2]]  = {ϕ, 1, {{ϕ0/Sqrt[2], ϕp}, {conj[ϕp], -ϕ0/Sqrt[2]}}, 0, 3, 1, -1};
RealScalars = {ϕ0};


(*----------------------------------------------*)
(*   DEFINITION                                 *)
(*----------------------------------------------*)
NameOfStates = {GaugeES, EWSB};

(* ----- before EWSB ----- *)
DEFINITION[GaugeES][LagrangianInput] = {
	{LagHC,      {AddHC -> True }},
	{LagNoHC,    {AddHC -> False}},
	{LagBSMHC,   {AddHC -> True }},
	{LagBSMNoHC, {AddHC -> False}}
};

(* Standard Model Lagrangian *)
LagHC      = -Yd conj[H].d.q - Ye conj[H].e.l - Yu u.q.H;
LagNoHC    = mu2 conj[H].H - 1/2 \[Lambda] conj[H].H.conj[H].H;

(* Lagrangian involving the new fields *)
LagBSMNoHC =  - 1/2 mϕ2 ϕ.ϕ \
	 - λ1 conj[H].ϕ.ϕ.H - λ2 conj[H].H.ϕ.ϕ - λ3 ϕ.ϕ.ϕ.ϕ;
LagBSMHC   =  - 1/2 mΨ Ψ.Ψ - mψψp ψ.ψp \
	 - λ4 conj[H].ψp.Ψ - λ5 H.ψ.Ψ - λ6 l.ϕ.ψp;

(* ----- after EWSB ----- *)
(* gauge sector mixing *)
DEFINITION[EWSB][GaugeSector] = {
	{{VB,     VWB[3]}, {VP, VZ}, ZZ},
	{{VWB[1], VWB[2]}, {VWp, conj[VWp]}, ZW}
};

(* VEVs *)
DEFINITION[EWSB][VEVs] = {
	(* Standard Model Higgs VEV *)
	{H0,
		{v, 1/Sqrt[2]},
		{Ah, \[ImaginaryI]/Sqrt[2]},
		{hh, 1/Sqrt[2]}
	}
};

(* mixing *)
DEFINITION[EWSB][MatterSector] = {
	(* Standard Model mixing *)
	{{{dL}, {conj[dR]}}, {{DL, Vd}, {DR, Ud}}},
	{{{uL}, {conj[uR]}}, {{UL, Vu}, {UR, Uu}}},
	{{{eL}, {conj[eR]}}, {{EL, Ve}, {ER, Ue}}}
	(* mixing of new fields can be added here *)
};

(* Dirac spinors *)
DEFINITION[EWSB][DiracSpinors] = {
	Fd -> {DL, conj[DR]},
	Fe -> {EL, conj[ER]},
	Fu -> {UL, conj[UR]},
	Fv -> {vL, 0}
};
