(* This file has been automatically generated by lagrangians.py *)
ParameterDefinitions = {
	(* new parameters *)
	{M22, {Description -> "BSM parameter M22",
			LaTeX -> "M_{2}^{2}",
			OutputName -> "M22",
			LesHouches -> {"BoehmMeVDM", 11},
			Real -> True
		}
	},
	{Mtst, {Description -> "BSM parameter M32",
			LaTeX -> "M_{3}^{2}",
			OutputName -> "Mtst",
			LesHouches -> {"BoehmMeVDM", 13},
			Real -> True
		}
	},
	{M42, {Description -> "BSM parameter M42",
			LaTeX -> "M_{4}^{2}",
			OutputName -> "M42",
			LesHouches -> {"BoehmMeVDM", 14},
			Real -> True
		}
	},
	{λ2, {Description -> "BSM parameter λ2",
			LaTeX -> "\\lambda_{2}",
			OutputName -> "lam2",
			LesHouches -> {"BoehmMeVDM", 22},
			Real -> True
		}
	},
	{λ3, {Description -> "BSM parameter λ3",
			LaTeX -> "\\lambda_{3}",
			OutputName -> "lam3",
			LesHouches -> {"BoehmMeVDM", 23},
			Real -> True
		}
	},
	{λ4, {Description -> "BSM parameter λ4",
			LaTeX -> "\\lambda_{4}",
			OutputName -> "lam4",
			LesHouches -> {"BoehmMeVDM", 24},
			Real -> True
		}
	},
	{λ5, {Description -> "BSM parameter λ5",
			LaTeX -> "\\lambda_{5}",
			OutputName -> "lam5",
			LesHouches -> {"BoehmMeVDM", 25},
			Real -> True
		}
	},
	{λ6, {Description -> "BSM parameter λ6",
			LaTeX -> "\\lambda_{6}",
			OutputName -> "lam6",
			LesHouches -> {"BoehmMeVDM", 26},
			Real -> True
		}
	},
	{λ7, {Description -> "BSM parameter λ7",
			LaTeX -> "\\lambda_{7}",
			OutputName -> "lam7",
			LesHouches -> {"BoehmMeVDM", 27},
			Real -> True
		}
	},
	{MasN, {Description -> "BSM parameter MasN",
			LaTeX -> "M_{MasN}",
			OutputName -> "MasN",
			LesHouches -> "MasN",
			Real -> True
		}
	},
	{λ8, {Description -> "BSM parameter λ8",
			LaTeX -> "\\lambda_{8}",
			OutputName -> "lam8",
			LesHouches -> "LAM8",
			Real -> True
		}
	},
	{Ybsm, {Description -> "BSM parameter Y",
			LaTeX -> "\\Y_{bsm}",
			OutputName -> "Ybsm",
			LesHouches -> {"Ybsm", 28},
			Real -> True
		}
	},

	{Uneu, {Description -> "Neutrino mixing matrix",
			LaTeX -> "U_\\nu",
			OutputName -> "Uneu",
			LesHouches -> "NUMIX"
		}
	},
	
	{UzetR, {Description -> "Mixing matrix real scalars",
			LaTeX -> "U_{\\zeta R}",
			OutputName -> "UzeR",
			LesHouches -> "ZERMIX",
			Real -> True
		}
	},
	
	{UzetI, {Description -> "Mixing matrix imaginary scalars",
			LaTeX -> "U_{\\zeta I}",
			OutputName -> "UzeI",
			LesHouches -> "ZEIMIX",
			Real -> True
		}
	},
	{Umaj, {Description -> "Majorana particles mixing matrix",
			LaTeX -> "U_{maj}",
			OutputName -> "Umaj",
			LesHouches -> "MAJMIX"
		}
	},

	(* Standard Model parameters *)
	{g1,        {Description -> "Hypercharge-Coupling"}},
	{g2,        {Description -> "Left-Coupling"}},
	{g3,        {Description -> "Strong-Coupling"}},
	{AlphaS,    {Description -> "Alpha Strong"}},
	{e,         {Description -> "electric charge"}},

	{Gf,        {Description -> "Fermi's constant"}},
	{aEWinv,    {Description -> "inverse weak coupling constant at mZ"}},

	{Yu,        {Description -> "Up-Yukawa-Coupling",
					DependenceNum -> Sqrt[2]/v * {
						{Mass[Fu,1], 0, 0},
						{0, Mass[Fu,2], 0},
						{0, 0, Mass[Fu,3]}
					}
				}
	},
	{Yd,        {Description -> "Down-Yukawa-Coupling",
					DependenceNum -> Sqrt[2]/v * {
						{Mass[Fd,1], 0, 0},
						{0, Mass[Fd,2], 0},
						{0, 0, Mass[Fd,3]}
					}
				}
	},
	{Ye,        {Description -> "Lepton-Yukawa-Coupling",
					DependenceNum -> Sqrt[2]/v * {
						{Mass[Fe,1], 0, 0},
						{0, Mass[Fe,2], 0},
						{0, 0, Mass[Fe,3]}
					}
				}
	},


	{mu2,       {Description -> "SM Mu Parameter"}},
	{\[Lambda], {Description -> "SM Higgs Selfcouplings",
					DependenceNum -> Mass[hh]^2/(v^2)
				}
	},
	{v,         {Description -> "EW-VEV",
					DependenceNum -> Sqrt[4 * Mass[VWp]^2/(g2^2)],
					DependenceSPheno -> None
				}
	},
	{mH2,       {Description -> "SM Higgs Mass Parameter"}},

	{ThetaW,    {Description -> "Weinberg-Angle",
					DependenceNum -> ArcSin[Sqrt[1 - Mass[VWp]^2/Mass[VZ]^2]]
				}
	},

	{ZZ,        {Description -> "Photon-Z Mixing Matrix"}},
	{ZW,        {Description -> "W Mixing Matrix",
					Dependence -> 1/Sqrt[2] {
						{1, 1},
						{\[ImaginaryI], -\[ImaginaryI]}
					}
				}
	},

	{Vu,        {Description -> "Left-Up-Mixing-Matrix"}},
	{Vd,        {Description -> "Left-Down-Mixing-Matrix"}},
	{Uu,        {Description -> "Right-Up-Mixing-Matrix"}},
	{Ud,        {Description -> "Right-Down-Mixing-Matrix"}},
	{Ve,        {Description -> "Left-Lepton-Mixing-Matrix"}},
	{Ue,        {Description -> "Right-Lepton-Mixing-Matrix"}}
};
