(* This file has been automatically generated by lagrangians.py *)
ParticleDefinitions[GaugeES] = {
	(* new fields *)
	{etap, {Description -> "BSM field η+",
			LaTeX -> "\\eta^+",
			OutputName -> "ep",
			ElectricCharge -> 1
		}
	},
	{eta0, {Description -> "BSM field η0",
			LaTeX -> "\\eta^0",
			PDG -> {930},
			FeynArtsNr -> 930,
			OutputName -> "e0",
			ElectricCharge -> 0
		}
	},
	{Nneut, {Description -> "BSM field Nneut",
			LaTeX -> "Nneut",
			OutputName -> "Nn",
			PDG -> {940,941,942},
			FeynArtsNr -> 940,
			ElectricCharge -> 0
		}
	},
	{chiR0, {Description -> "BSM field χR0",
			LaTeX -> "\\chi_R^0",
			OutputName -> "cR",
			PDG -> {931},
			FeynArtsNr -> 931,
			ElectricCharge -> 0
		}
	},
	{chiI0, {Description -> "BSM field χI0",
			LaTeX -> "\\chi_I^0",
			OutputName -> "cI",
			PDG -> {932},
			FeynArtsNr -> 932,
			ElectricCharge -> 0
		}
	},

	(* Standard Model *)
	{H0, {
			PDG -> {0},
			Width -> 0,
			Mass -> Automatic,
			FeynArtsNr -> 1,
			LaTeX -> "H^0",
			OutputName -> "H0"
		}
	},
	{Hp, {
			PDG -> {0},
			Width -> 0,
			Mass -> Automatic,
			FeynArtsNr -> 2,
			LaTeX -> "H^+",
			OutputName -> "Hp"
		}
	},

	{VB,  {Description -> "B-Boson"}},
	{VG,  {Description -> "Gluon"}},
	{VWB, {Description -> "W-Bosons"}},
	{gB,  {Description -> "B-Boson Ghost"}},
	{gG,  {Description -> "Gluon Ghost"}},
	{gWB, {Description -> "W-Boson Ghost"}}
};

ParticleDefinitions[EWSB] = {
	(* new fields *)
	(* to be completed manually *)

	{etap, {Description -> "BSM field etap",
			LaTeX -> "\\eta^+",
			OutputName -> "ep",
			PDG -> {901},
			FeynArtsNr -> 901,
			ElectricCharge -> 1
		}
	},

	{Fnu,  {Description -> "Neutrinos",
			Mass -> LesHouches
		}
	},
	{zetaR, {Description -> "BSM scalar zetaR",
			LaTeX -> "\\zeta_R",
			OutputName -> "zR",
			PDG -> {902, 903},
			FeynArtsNr -> 902,
			ElectricCharge -> 0
		}
	},

	{zetaI, {Description -> "BSM scalar zetaI",
			LaTeX -> "\\zeta_I",
			OutputName -> "zI",
			PDG -> {904, 905},
			FeynArtsNr -> 904,
			ElectricCharge -> 0
		}
	},
	
	{FmaN, {Description -> "BSM field FmaN",
			LaTeX -> "FmaN",
			OutputName -> "Fm",
			PDG -> {910, 911, 912},
			FeynArtsNr -> 910,
			ElectricCharge -> 0
		}
	},
	
	(* Standard Model *)
	{hh,   {Description -> "Higgs",
			PDG -> {25},
			PDG.IX -> {101000001}
		}
	},
	{Ah,   {Description -> "Pseudo-Scalar Higgs",
			PDG -> {0},
			PDG.IX -> {0},
			Mass -> {0},
			Width -> {0}
		}
	},
	{Hp,   {Description -> "Charged Higgs",
			PDG -> {0},
			PDG.IX -> {0},
			Width -> {0},
			Mass -> {0},
			LaTeX -> {"H^+", "H^-"},
			OutputName -> {"Hp", "Hm"},
			ElectricCharge -> 1
		}
	},

	{VP,   {Description -> "Photon"}},
	{VZ,   {Description -> "Z-Boson",
			Goldstone -> Ah
		}
	},
	{VG,   {Description -> "Gluon"}},
	{VWp,  {Description -> "W+ - Boson",
			Goldstone -> Hp
		}
	},
	{gP,   {Description -> "Photon Ghost"}},
	{gWp,  {Description -> "Positive W+ - Boson Ghost"}},
	{gWpC, {Description -> "Negative W+ - Boson Ghost"}},
	{gZ,   {Description -> "Z-Boson Ghost"}},
	{gG,   {Description -> "Gluon Ghost"}},

	{Fd,   {Description -> "Down-Quarks"}},
	{Fu,   {Description -> "Up-Quarks"}},
	{Fe,   {Description -> "Leptons"}}
};

WeylFermionAndIndermediate = {
	(* new fields *)
	{eta, {LaTeX -> "\\eta"}},
	{majN, {LaTeX -> "N"}},
	{eta0R, {LaTeX -> "\\eta0R"}},
	{eta0I, {LaTeX -> "\\eta0I"}},
	{chiR0, {LaTeX -> "\\chiR0"}},
	{chiI0, {LaTeX -> "\\chiI0"}},
	
	
	{zetaR, {LaTeX -> "\\zetaR"}},
	{zetaI, {LaTeX -> "\\zetaI"}},

	(* Standard Model *)
	{H, {
			PDG -> {0},
			Width -> 0,
			Mass -> Automatic,
			LaTeX -> "H",
			OutputName -> ""
		}
	},

	{dR,  {LaTeX -> "d_R"}},
	{eR,  {LaTeX -> "e_R"}},
	{l,   {LaTeX -> "l"}},
	{uR,  {LaTeX -> "u_R"}},
	{q,   {LaTeX -> "q"}},
	{eL,  {LaTeX -> "e_L"}},
	{dL,  {LaTeX -> "d_L"}},
	{uL,  {LaTeX -> "u_L"}},
	{vL,  {LaTeX -> "\\nu_L"}},

	{DR,  {LaTeX -> "D_R"}},
	{ER,  {LaTeX -> "E_R"}},
	{UR,  {LaTeX -> "U_R"}},
	{EL,  {LaTeX -> "E_L"}},
	{DL,  {LaTeX -> "D_L"}},
	{UL,  {LaTeX -> "U_L"}}
};
