(* This file has been automatically generated by lagrangians.py *)
Off[General::spell]

Model`Name = "BoehmMeVDM";
Model`NameLaTeX = "BoehmMeVDM";
Model`Authors = "lagrangians.py (automatically generated)";
Model`Date = "2018-12-12";

(*-------------------------------------------*)
(*   particle content                        *)
(*-------------------------------------------*)

(* global symmetries *)
(* discrete ℤ₂ symmetry *)
Global[[1]] = {Z[2], Z2};


(* gauge groups *)
Gauge[[1]] = {B,   U[1], hypercharge, g1, False, 1};
Gauge[[2]] = {WB, SU[2], left,        g2, True,  1};
Gauge[[3]] = {G,  SU[3], color,       g3, False, 1};

(* matter fields *)
(*                   {name, gens, components, Y/2,  SU(2), SU(3), global} *)
(* Standard Model *)
FermionFields[[1]] = {q,    3,    {uL, dL},    1/6, 2,     3,     1};
FermionFields[[2]] = {l,    3,    {vL, eL},   -1/2, 2,     1,     1};
FermionFields[[3]] = {d,    3,    conj[dR],    1/3, 1,    -3,     1};
FermionFields[[4]] = {u,    3,    conj[uR],   -2/3, 1,    -3,     1};
FermionFields[[5]] = {e,    3,    conj[eR],      1, 1,     1,     1};

ScalarFields[[1]]  = {H,    1,    {Hp, H0},    1/2, 2,     1,     1};

(* new fields *)
FermionFields[[6]] = {majN, 3,    Nneut,           0, 1,      1, -1};
ScalarFields[[2]]  = {eta,  1,    {etap, eta0}, 1/2, 2,    1, -1};
ScalarFields[[3]]  = {chiR, 1,    chiR0,        0, 1,      1, -1};
ScalarFields[[4]]  = {chiI, 1,    chiI0,        0, 1,      1, -1};
RealScalars = {chiR, chiI};


(*----------------------------------------------*)
(*   DEFINITION                                 *)
(*----------------------------------------------*)
NameOfStates = {GaugeES, EWSB};

(* ----- before EWSB ----- *)
DEFINITION[GaugeES][LagrangianInput] = {
	{LagHC,      {AddHC -> True }},
	{LagNoHC,    {AddHC -> False}},
	{LagBSMHC,   {AddHC -> True }},
	{LagBSMNoHC, {AddHC -> False}}
};

(* Standard Model Lagrangian *)
LagHC      = -Yd conj[H].d.q - Ye conj[H].e.l - Yu u.q.H;
LagNoHC    = mu2 conj[H].H - 1/2 λ conj[H].H.conj[H].H;

(* Lagrangian involving the new fields *)
LagBSMNoHC =  - M22 conj[eta].eta - 1/2 Mtst chiR.chiR - 1/2 M42 chiI.chiI (*- 1/2 M42 chiR.chiR + 1/2 M42 chiI.chiI*) \
    - 1/2 λ2 conj[eta].eta.conj[eta].eta - 1/8 λ3 chiR.chiR.chiR.chiR - 1/8 λ3 chiI.chiI.chiI.chiI - 1/4 λ3 chiR.chiR.chiI.chiI \
    - λ4 conj[eta].eta.conj[H].H - λ5 conj[eta].H.conj[H].eta \
    - 1/2 λ6 conj[H].H.chiR.chiR - 1/2 λ6 conj[H].H.chiI.chiI - 1/2 λ7 conj[eta].eta.chiR.chiR - 1/2 λ7 conj[eta].eta.chiI.chiI;
LagBSMHC   = - 1/Sqrt[2] Ybsm conj[eta].H.chiR + \[ImaginaryI]/Sqrt[2] Ybsm conj[eta].H.chiI \
	 - 1/2 MasN majN.majN \
	 - λ8 l.eta.majN;

(* ----- after EWSB ----- *)
(* gauge sector mixing *)
DEFINITION[EWSB][GaugeSector] = {
	{{VB,     VWB[3]}, {VP, VZ}, ZZ},
	{{VWB[1], VWB[2]}, {VWp, conj[VWp]}, ZW}
};

(* VEVs *)
DEFINITION[EWSB][VEVs] = {
	(* Standard Model Higgs VEV *)
	{H0,
		{v, 1/Sqrt[2]},
		{Ah, \[ImaginaryI]/Sqrt[2]},
		{hh, 1/Sqrt[2]}
	},
	(* BSM VeV to obtain real and imaginary parts*)
	{eta0,
		{0, 0},
		{eta0I, \[ImaginaryI]/Sqrt[2]},
		{eta0R, 1/Sqrt[2]}
	}
};

(* mixing *)
DEFINITION[EWSB][MatterSector] = {
	(* Standard Model mixing *)
	{{{dL}, {conj[dR]}}, {{DL, Vd}, {DR, Ud}}},
	{{{uL}, {conj[uR]}}, {{UL, Vu}, {UR, Uu}}},
	{{{eL}, {conj[eR]}}, {{EL, Ve}, {ER, Ue}}},
	(* mixing of new fields can be added here, take care to check names of mixing matrices, not U[name] *)
	{{vL}, {VL, Uneu}},
	{{eta0R, chiR0}, {zetaR, UzetR}},
	{{eta0I, chiI0}, {zetaI, UzetI}},
	{{Nneut}, {Nnmix, Umaj}}	
};

(* Dirac spinors *)
DEFINITION[EWSB][DiracSpinors] = {
	Fd -> {DL, conj[DR]},
	Fe -> {EL, conj[ER]},
	Fu -> {UL, conj[UR]},
	Fnu -> {VL, conj[VL]},
	(* New fields *)
	FmaN -> {Nnmix, conj[Nnmix]}
};
